name: Deploy to GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install node_modules
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to gh-pages branch
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: ./dist
          force: true
          github_token: ${{ secrets.GH_PAGES }}